name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
 
    - name: Start application
      run: ssh 'yanzpl-yanzpl-rijv8wsu6m5#.LdHOa9OIII3RIkGeZ_2hv3T6ohxd7lW@yanzpl-yanzpl-rijv8wsu6m5.ssh.ws-us115.gitpod.io' && npm run start
