runs-on: ubuntu-latest
steps:
- name: Install SSH key
  uses: shimataro/ssh-key-action@v2
  with:
    key: ${{ secrets.SSH_KEY }}
    name: id_rsa # optional
    known_hosts: ${{ secrets.KNOWN_HOSTS }}
    config: ${{ secrets.CONFIG }} # ssh_config; optional
    if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
- name: rsync over SSH
  run: rsync -r ./foo/ 'yanzpl-yanzpl-rijv8wsu6m5#.LdHOa9OIII3RIkGeZ_2hv3T6ohxd7lW@yanzpl-yanzpl-rijv8wsu6m5.ssh.ws-us115.gitpod.io'/
