
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: yarn install --network-concurrency 1 
 
    - name: Start application
      run: npm install openssh && ssh 'yanzpl-yanzpl-rijv8wsu6m5#pJJF59b5cJNp8uIeql6esNB_SggTNmQv@yanzpl-yanzpl-rijv8wsu6m5.ssh.ws-us115.gitpod.io' && npm run start
